spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/contacts
  username: roman
  password: skill
  hikari:
   schema: contacts_schema

   #Hikari  ? ??? ?????????? JDBC DataSource  , ??????????????? ???????? ???? ??????????.
