server:
 port: 8080

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/contacts?currentSchema=contacts_schema
  username: user
  password: password


# URL локального приложения:
# http://localhost:8080/